spring:
  application:
    name: library-management-system
  profiles:
    include:
      - email
      - db
      - common
      - card
  servlet:
    multipart:
      max-file-size: 100MB
server:
  port: 8080

